// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXGzHRoRlzw6bv8ecmH1wXV_uWWv7bN6k',
    appId: '1:350459347996:web:d0ac7cfcfd21802243cbd9',
    messagingSenderId: '350459347996',
    projectId: 'interlaken-service',
    authDomain: 'interlaken-service.firebaseapp.com',
    storageBucket: 'interlaken-service.firebasestorage.app',
    measurementId: 'G-14S9XEJEJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHy2aakfMaP8HFsAVW-o2TJihpPPqsoBE',
    appId: '1:350459347996:android:d350b65e5ed19c0343cbd9',
    messagingSenderId: '350459347996',
    projectId: 'interlaken-service',
    storageBucket: 'interlaken-service.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDnbnpL2mvaSr6oZwwYUEye0Kc1l6s4f0',
    appId: '1:350459347996:ios:50c13623789a1f3343cbd9',
    messagingSenderId: '350459347996',
    projectId: 'interlaken-service',
    storageBucket: 'interlaken-service.firebasestorage.app',
    iosBundleId: 'com.example.interlakenService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDnbnpL2mvaSr6oZwwYUEye0Kc1l6s4f0',
    appId: '1:350459347996:ios:50c13623789a1f3343cbd9',
    messagingSenderId: '350459347996',
    projectId: 'interlaken-service',
    storageBucket: 'interlaken-service.firebasestorage.app',
    iosBundleId: 'com.example.interlakenService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXGzHRoRlzw6bv8ecmH1wXV_uWWv7bN6k',
    appId: '1:350459347996:web:8e273125df3957f543cbd9',
    messagingSenderId: '350459347996',
    projectId: 'interlaken-service',
    authDomain: 'interlaken-service.firebaseapp.com',
    storageBucket: 'interlaken-service.firebasestorage.app',
    measurementId: 'G-G22C56WC8B',
  );
}
